# Generated by Django 3.2.5 on 2021-08-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
